### PR TITLE
Typo fixed

### PR DESCRIPTION
**Pull request by michaelwechner**

### CODE REVIEW

**Comment by metaodi** [comment]
Thank you!

**Comment by michaelwechner** [comment]
Sure!

Btw, I think there is one more typo at the bottom of the README.md, I think it should read "Messenger-Dienst" instead "Messanger-Dienst", right?

**Comment by metaodi** [comment]
You're right, thanks. Just fixed it 😃

**Comment by michaelwechner** [comment]
very cool, thanks! :-)

**Pull request merged**
